# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

# Pre-release hooks for cleaning up and preparing the environment
before:
  hooks:
    # Ensuring go.mod file is tidy
    - go mod tidy
    # Optional: Uncomment if your project requires go generate
    # - go generate ./...

# Configuration for building the project
builds:
  - env:
      - CGO_ENABLED=0  # Disabling CGO for cross-platform compatibility
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64  # Targeting amd64 architecture
    # Optional: Including arm64 architecture for Apple Silicon and others
    # - arm64

# Archive configuration for packaging the builds
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip  # Using ZIP format for Windows archives

# Changelog configuration to customize release notes
changelog:
  sort: asc  # Sorting changes in ascending order
  filters:
    exclude:
      - "^docs:"  # Excluding documentation changes
      - "^test:"  # Excluding test-related changes

# Optional: Add checksum and signing configurations to enhance security
checksum:
  name_template: 'checksums.txt'
# Optional: Sign artifacts using a PGP key
#signs:
#  artifacts: checksum
