name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

_defaults_:
  _container_:
    image: ghcr.io/wishabi/ci-build-environment:ruby-3.2-bookworm
    credentials:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GHCR_TOKEN }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}